Attempt 2

diff --git a/src/base-ubuntu/.devcontainer/Dockerfile b/src/base-ubuntu/.devcontainer/Dockerfile
--- a/src/base-ubuntu/.devcontainer/Dockerfile
+++ b/src/base-ubuntu/.devcontainer/Dockerfile
@@ -5,9 +5,10 @@ RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* 
 	&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
 ENV LANG=en_US.utf8
 
-# If exists, remove 'ubuntu' user
-RUN	if id "ubuntu" &>/dev/null; then \
-		echo "Deleting user 'ubuntu'" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user"; \  
+# Remove 'ubuntu' user if it exists
+RUN if id "ubuntu" &>/dev/null; then \
+		echo "Deleting user 'ubuntu'"; \
+		deluser --remove-home ubuntu || echo "Failed to delete ubuntu user"; \
 	else \
-		echo "User 'ubuntu' does not exist"; \ 
-	fi;
+		echo "User 'ubuntu' does not exist"; \
+	fi
